# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c785c1309e1251856f9982d8e26cd2c0bd08870e89e96e45c1995f42d4f5b5f148a0ff310093962fd918ba7b325b841b66207c46585b3e83001455c1a18ab91

test:
  secret_key_base: 678f31f3e1637b152b180de216e770e1b90ca6881daad3ddaedbb3aa0479066194373b75accd4b7860012c2d819c78ff829c273afc92f356359137f3805e5397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
